apiVersion: host.boundary.upbound.io/v1alpha1
kind: CatalogStatic
metadata:
  annotations:
    meta.upbound.io/example-id: host/v1alpha1/catalogstatic
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: My first host catalog!
    name: My catalog
    scopeId: ${boundary_scope.project.id}

---

apiVersion: boundary.boundary.upbound.io/v1alpha1
kind: Scope
metadata:
  annotations:
    meta.upbound.io/example-id: host/v1alpha1/catalogstatic
  labels:
    testing.upbound.io/example-name: org
  name: org
spec:
  forProvider:
    autoCreateAdminRole: true
    autoCreateDefaultRole: true
    description: My first scope!
    name: organization_one
    scopeId: ${boundary_scope.global.id}

---

apiVersion: boundary.boundary.upbound.io/v1alpha1
kind: Scope
metadata:
  annotations:
    meta.upbound.io/example-id: host/v1alpha1/catalogstatic
  labels:
    testing.upbound.io/example-name: project
  name: project
spec:
  forProvider:
    autoCreateAdminRole: true
    description: My first scope!
    name: project_one
    scopeId: ${boundary_scope.org.id}
