apiVersion: host.boundary.upbound.io/v1alpha1
kind: SetPlugin
metadata:
  annotations:
    meta.upbound.io/example-id: host/v1alpha1/setplugin
  labels:
    testing.upbound.io/example-name: web
  name: web
spec:
  forProvider:
    attributesJson: ${jsonencode({ "filters" = ["tag:service-type=web"] })}
    hostCatalogId: ${boundary_host_catalog_plugin.aws_example.id}
    name: My web host set plugin

---

apiVersion: host.boundary.upbound.io/v1alpha1
kind: CatalogPlugin
metadata:
  annotations:
    meta.upbound.io/example-id: host/v1alpha1/setplugin
  labels:
    testing.upbound.io/example-name: aws_example
  name: aws-example
spec:
  forProvider:
    attributesJson: ${jsonencode({ "region" = "us-east-1" })}
    description: My first host catalog!
    name: My aws catalog
    pluginName: aws
    scopeId: ${boundary_scope.project.id}
    secretsJsonSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system

---

apiVersion: host.boundary.upbound.io/v1alpha1
kind: CatalogPlugin
metadata:
  annotations:
    meta.upbound.io/example-id: host/v1alpha1/setplugin
  labels:
    testing.upbound.io/example-name: azure_example
  name: azure-example
spec:
  forProvider:
    attributesJson: |-
      ${jsonencode({
          "disable_credential_rotation" = "true",
          "tenant_id"                   = "ARM_TENANT_ID",
          "subscription_id"             = "ARM_SUBSCRIPTION_ID",
          "client_id"                   = "ARM_CLIENT_ID"
        })}
    description: My second host catalog!
    name: My azure catalog
    pluginName: azure
    scopeId: ${boundary_scope.project.id}
    secretsJsonSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system

---

apiVersion: boundary.boundary.upbound.io/v1alpha1
kind: Scope
metadata:
  annotations:
    meta.upbound.io/example-id: host/v1alpha1/setplugin
  labels:
    testing.upbound.io/example-name: org
  name: org
spec:
  forProvider:
    autoCreateAdminRole: true
    autoCreateDefaultRole: true
    description: My first scope!
    name: organization_one
    scopeId: global

---

apiVersion: boundary.boundary.upbound.io/v1alpha1
kind: Scope
metadata:
  annotations:
    meta.upbound.io/example-id: host/v1alpha1/setplugin
  labels:
    testing.upbound.io/example-name: project
  name: project
spec:
  forProvider:
    autoCreateAdminRole: true
    description: My first scope!
    name: project_one
    scopeId: ${boundary_scope.org.id}
