apiVersion: host.boundary.upbound.io/v1alpha1
kind: Static
metadata:
  annotations:
    meta.upbound.io/example-id: host/v1alpha1/static
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    address: 10.0.0.1
    description: My first host!
    hostCatalogIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: example_host

---

apiVersion: host.boundary.upbound.io/v1alpha1
kind: CatalogStatic
metadata:
  annotations:
    meta.upbound.io/example-id: host/v1alpha1/static
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: My first host catalog!
    name: My catalog
    scopeIdSelector:
      matchLabels:
        testing.upbound.io/example-name: project

---

apiVersion: boundary.boundary.upbound.io/v1alpha1
kind: Scope
metadata:
  annotations:
    meta.upbound.io/example-id: host/v1alpha1/static
  labels:
    testing.upbound.io/example-name: org
  name: org
spec:
  forProvider:
    autoCreateAdminRole: true
    autoCreateDefaultRole: true
    description: My first scope!
    name: organization_one
    scopeId: global

---

apiVersion: boundary.boundary.upbound.io/v1alpha1
kind: Scope
metadata:
  annotations:
    meta.upbound.io/example-id: host/v1alpha1/static
  labels:
    testing.upbound.io/example-name: project
  name: project
spec:
  forProvider:
    autoCreateAdminRole: true
    description: My first scope!
    name: project_one
    scopeId: ${boundary_scope.org.id}
