apiVersion: host.boundary.upbound.io/v1alpha1
kind: CatalogPlugin
metadata:
  annotations:
    meta.upbound.io/example-id: host/v1alpha1/catalogplugin
  labels:
    testing.upbound.io/example-name: aws_example
  name: aws-example
spec:
  forProvider:
    attributesJson: ${jsonencode({ "region" = "us-east-1" })}
    description: My first host catalog!
    name: My aws catalog
    pluginName: aws
    scopeId: ${boundary_scope.project.id}
    secretsJsonSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system

---

apiVersion: main.boundary.upbound.io/v1alpha1
kind: Scope
metadata:
  annotations:
    meta.upbound.io/example-id: host/v1alpha1/catalogplugin
  labels:
    testing.upbound.io/example-name: org
  name: org
spec:
  forProvider:
    autoCreateAdminRole: true
    autoCreateDefaultRole: true
    description: My first scope!
    name: organization_one
    scopeIdSelector:
      matchLabels:
        testing.upbound.io/example-name: global

---

apiVersion: main.boundary.upbound.io/v1alpha1
kind: Scope
metadata:
  annotations:
    meta.upbound.io/example-id: host/v1alpha1/catalogplugin
  labels:
    testing.upbound.io/example-name: project
  name: project
spec:
  forProvider:
    autoCreateAdminRole: true
    description: My first scope!
    name: project_one
    scopeIdSelector:
      matchLabels:
        testing.upbound.io/example-name: org
