apiVersion: boundary.boundary.upbound.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: boundary/v1alpha1/group
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: My first group!
    memberIds:
    - ${boundary_user.foo.id}
    name: My group
    scopeId: ${boundary_scope.org.id}

---

apiVersion: boundary.boundary.upbound.io/v1alpha1
kind: Scope
metadata:
  annotations:
    meta.upbound.io/example-id: boundary/v1alpha1/group
  labels:
    testing.upbound.io/example-name: org
  name: org
spec:
  forProvider:
    autoCreateAdminRole: true
    autoCreateDefaultRole: true
    description: My first scope!
    name: organization_one
    scopeId: global

---

apiVersion: boundary.boundary.upbound.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: boundary/v1alpha1/group
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    description: foo user
    scopeId: ${boundary_scope.org.id}
