apiVersion: boundary.boundary.upbound.io/v1alpha1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: boundary/v1alpha1/role
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: My first role!
    name: My role
    scopeIdSelector:
      matchLabels:
        testing.upbound.io/example-name: org

---

apiVersion: boundary.boundary.upbound.io/v1alpha1
kind: Scope
metadata:
  annotations:
    meta.upbound.io/example-id: boundary/v1alpha1/role
  labels:
    testing.upbound.io/example-name: org
  name: org
spec:
  forProvider:
    autoCreateAdminRole: true
    autoCreateDefaultRole: true
    description: My first scope!
    name: organization_one
    scopeId: global
