apiVersion: credential.boundary.upbound.io/v1alpha1
kind: JSON
metadata:
  annotations:
    meta.upbound.io/example-id: credential/v1alpha1/json
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    credentialStoreId: ${boundary_credential_store_static.example.id}
    description: My first json credential!
    name: example_json
    objectSecretRef:
      key: attribute.object.json
      name: example-secret
      namespace: upbound-system

---

apiVersion: credential.boundary.upbound.io/v1alpha1
kind: StoreStatic
metadata:
  annotations:
    meta.upbound.io/example-id: credential/v1alpha1/json
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: My first static credential store!
    name: example_static_credential_store
    scopeId: ${boundary_scope.project.id}

---

apiVersion: main.boundary.upbound.io/v1alpha1
kind: Scope
metadata:
  annotations:
    meta.upbound.io/example-id: credential/v1alpha1/json
  labels:
    testing.upbound.io/example-name: org
  name: org
spec:
  forProvider:
    autoCreateAdminRole: true
    autoCreateDefaultRole: true
    description: global scope
    name: organization_one
    scopeId: global

---

apiVersion: main.boundary.upbound.io/v1alpha1
kind: Scope
metadata:
  annotations:
    meta.upbound.io/example-id: credential/v1alpha1/json
  labels:
    testing.upbound.io/example-name: project
  name: project
spec:
  forProvider:
    autoCreateAdminRole: true
    description: My first scope!
    name: project_one
    scopeId: ${boundary_scope.org.id}
