// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Method) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MethodLdap) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MethodOidc) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MethodPassword) Hub() {}
