// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	resource "github.com/crossplane/upjet/pkg/resource"
	errors "github.com/pkg/errors"
	v1alpha1 "github.com/releaseband/crossplane-provider-boundary/apis/main/v1alpha1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Role.
func (mg *Role) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var mrsp reference.MultiResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.PrincipalIds),
		Extract:       resource.ExtractParamPath("id", true),
		References:    mg.Spec.ForProvider.PrincipalIdsRefs,
		Selector:      mg.Spec.ForProvider.PrincipalIdsSelector,
		To: reference.To{
			List:    &GroupList{},
			Managed: &Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PrincipalIds")
	}
	mg.Spec.ForProvider.PrincipalIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.PrincipalIdsRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ScopeID),
		Extract:      resource.ExtractParamPath("id", true),
		Reference:    mg.Spec.ForProvider.ScopeIDRef,
		Selector:     mg.Spec.ForProvider.ScopeIDSelector,
		To: reference.To{
			List:    &v1alpha1.ScopeList{},
			Managed: &v1alpha1.Scope{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ScopeID")
	}
	mg.Spec.ForProvider.ScopeID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ScopeIDRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.PrincipalIds),
		Extract:       resource.ExtractParamPath("id", true),
		References:    mg.Spec.InitProvider.PrincipalIdsRefs,
		Selector:      mg.Spec.InitProvider.PrincipalIdsSelector,
		To: reference.To{
			List:    &GroupList{},
			Managed: &Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PrincipalIds")
	}
	mg.Spec.InitProvider.PrincipalIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.PrincipalIdsRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ScopeID),
		Extract:      resource.ExtractParamPath("id", true),
		Reference:    mg.Spec.InitProvider.ScopeIDRef,
		Selector:     mg.Spec.InitProvider.ScopeIDSelector,
		To: reference.To{
			List:    &v1alpha1.ScopeList{},
			Managed: &v1alpha1.Scope{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ScopeID")
	}
	mg.Spec.InitProvider.ScopeID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ScopeIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Target.
func (mg *Target) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ScopeID),
		Extract:      resource.ExtractParamPath("id", true),
		Reference:    mg.Spec.ForProvider.ScopeIDRef,
		Selector:     mg.Spec.ForProvider.ScopeIDSelector,
		To: reference.To{
			List:    &v1alpha1.ScopeList{},
			Managed: &v1alpha1.Scope{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ScopeID")
	}
	mg.Spec.ForProvider.ScopeID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ScopeIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ScopeID),
		Extract:      resource.ExtractParamPath("id", true),
		Reference:    mg.Spec.InitProvider.ScopeIDRef,
		Selector:     mg.Spec.InitProvider.ScopeIDSelector,
		To: reference.To{
			List:    &v1alpha1.ScopeList{},
			Managed: &v1alpha1.Scope{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ScopeID")
	}
	mg.Spec.InitProvider.ScopeID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ScopeIDRef = rsp.ResolvedReference

	return nil
}
