/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	resource "github.com/crossplane/upjet/pkg/resource"
	errors "github.com/pkg/errors"
	v1alpha1 "github.com/releaseband/crossplane-provider-boundary/apis/auth/v1alpha1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Group.
func (mg *Group) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.AuthMethodID),
		Extract:      resource.ExtractParamPath("id", true),
		Reference:    mg.Spec.ForProvider.AuthMethodIDRef,
		Selector:     mg.Spec.ForProvider.AuthMethodIDSelector,
		To: reference.To{
			List:    &v1alpha1.MethodOidcList{},
			Managed: &v1alpha1.MethodOidc{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.AuthMethodID")
	}
	mg.Spec.ForProvider.AuthMethodID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AuthMethodIDRef = rsp.ResolvedReference

	return nil
}
