// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type GroupLdapInitParameters struct {

	// (String) The resource ID for the auth method.
	// The resource ID for the auth method.
	AuthMethodID *string `json:"authMethodId,omitempty" tf:"auth_method_id,omitempty"`

	// (String) The managed group description.
	// The managed group description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (List of String) The list of groups that make up the managed group.
	// The list of groups that make up the managed group.
	GroupNames []*string `json:"groupNames,omitempty" tf:"group_names,omitempty"`

	// (String) The managed group name. Defaults to the resource name.
	// The managed group name. Defaults to the resource name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type GroupLdapObservation struct {

	// (String) The resource ID for the auth method.
	// The resource ID for the auth method.
	AuthMethodID *string `json:"authMethodId,omitempty" tf:"auth_method_id,omitempty"`

	// (String) The managed group description.
	// The managed group description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (List of String) The list of groups that make up the managed group.
	// The list of groups that make up the managed group.
	GroupNames []*string `json:"groupNames,omitempty" tf:"group_names,omitempty"`

	// (String) The ID of the group.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The managed group name. Defaults to the resource name.
	// The managed group name. Defaults to the resource name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type GroupLdapParameters struct {

	// (String) The resource ID for the auth method.
	// The resource ID for the auth method.
	// +kubebuilder:validation:Optional
	AuthMethodID *string `json:"authMethodId,omitempty" tf:"auth_method_id,omitempty"`

	// (String) The managed group description.
	// The managed group description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (List of String) The list of groups that make up the managed group.
	// The list of groups that make up the managed group.
	// +kubebuilder:validation:Optional
	GroupNames []*string `json:"groupNames,omitempty" tf:"group_names,omitempty"`

	// (String) The managed group name. Defaults to the resource name.
	// The managed group name. Defaults to the resource name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// GroupLdapSpec defines the desired state of GroupLdap
type GroupLdapSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     GroupLdapParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GroupLdapInitParameters `json:"initProvider,omitempty"`
}

// GroupLdapStatus defines the observed state of GroupLdap.
type GroupLdapStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GroupLdapObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// GroupLdap is the Schema for the GroupLdaps API. The managed group resource allows you to configure a Boundary group.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,boundary}
type GroupLdap struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.authMethodId) || (has(self.initProvider) && has(self.initProvider.authMethodId))",message="spec.forProvider.authMethodId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.groupNames) || (has(self.initProvider) && has(self.initProvider.groupNames))",message="spec.forProvider.groupNames is a required parameter"
	Spec   GroupLdapSpec   `json:"spec"`
	Status GroupLdapStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GroupLdapList contains a list of GroupLdaps
type GroupLdapList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GroupLdap `json:"items"`
}

// Repository type metadata.
var (
	GroupLdap_Kind             = "GroupLdap"
	GroupLdap_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GroupLdap_Kind}.String()
	GroupLdap_KindAPIVersion   = GroupLdap_Kind + "." + CRDGroupVersion.String()
	GroupLdap_GroupVersionKind = CRDGroupVersion.WithKind(GroupLdap_Kind)
)

func init() {
	SchemeBuilder.Register(&GroupLdap{}, &GroupLdapList{})
}
