apiVersion: alias.boundary.upbound.io/v1alpha1
kind: Target
metadata:
  annotations:
    meta.upbound.io/example-id: alias/v1alpha1/target
  labels:
    testing.upbound.io/example-name: example_alias_target
  name: example-alias-target
spec:
  forProvider:
    authorizeSessionHostId: ${boundary_host_static.bar.id}
    description: Example alias to target foo using host boundary_host_static.bar
    destinationId: ${boundary_target.foo.id}
    name: example_alias_target
    scopeId: global
    value: example.bar.foo.boundary

---

apiVersion: host.boundary.upbound.io/v1alpha1
kind: CatalogStatic
metadata:
  annotations:
    meta.upbound.io/example-id: alias/v1alpha1/target
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    description: test catalog
    name: test
    scopeId: ${boundary_scope.project.id}

---

apiVersion: host.boundary.upbound.io/v1alpha1
kind: SetStatic
metadata:
  annotations:
    meta.upbound.io/example-id: alias/v1alpha1/target
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    hostCatalogId: ${boundary_host_catalog_static.foo.id}
    hostIds:
    - ${boundary_host_static.foo.id}
    - ${boundary_host_static.bar.id}
    name: foo

---

apiVersion: host.boundary.upbound.io/v1alpha1
kind: Static
metadata:
  annotations:
    meta.upbound.io/example-id: alias/v1alpha1/target
  labels:
    testing.upbound.io/example-name: bar
  name: bar
spec:
  forProvider:
    address: 127.0.0.1
    hostCatalogId: ${boundary_host_catalog_static.foo.id}
    name: bar

---

apiVersion: host.boundary.upbound.io/v1alpha1
kind: Static
metadata:
  annotations:
    meta.upbound.io/example-id: alias/v1alpha1/target
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    address: 10.0.0.1
    hostCatalogId: ${boundary_host_catalog_static.foo.id}
    name: foo

---

apiVersion: boundary.boundary.upbound.io/v1alpha1
kind: Scope
metadata:
  annotations:
    meta.upbound.io/example-id: alias/v1alpha1/target
  labels:
    testing.upbound.io/example-name: org
  name: org
spec:
  forProvider:
    autoCreateAdminRole: true
    autoCreateDefaultRole: true
    description: global scope
    name: organization_one
    scopeId: global

---

apiVersion: boundary.boundary.upbound.io/v1alpha1
kind: Scope
metadata:
  annotations:
    meta.upbound.io/example-id: alias/v1alpha1/target
  labels:
    testing.upbound.io/example-name: project
  name: project
spec:
  forProvider:
    autoCreateAdminRole: true
    description: My first scope!
    name: project_one
    scopeId: ${boundary_scope.org.id}

---

apiVersion: boundary.boundary.upbound.io/v1alpha1
kind: Target
metadata:
  annotations:
    meta.upbound.io/example-id: alias/v1alpha1/target
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    defaultPort: "22"
    description: Foo target
    hostSourceIds:
    - ${boundary_host_set_static.foo.id}
    name: foo
    scopeId: ${boundary_scope.project.id}
    type: tcp
